// 用途：将当前逻辑表结构导出为可直接纳入 Unity 项目的 C# 数据类。
// 编写日期：2026-10-06
// 作者：Codex（按用户需求修改）

using System.Text;
using TableTool.Core.Models;
using TableTool.Core.Parsing;

namespace TableTool.Serialization;

public static class CSharpExporter
{
    public static string Export(TableDocument document)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// 用途：由 UnityTableTool 根据配置表结构生成的数据类。");
        builder.AppendLine("// 编写日期：由打表时生成。");
        builder.AppendLine("// 作者：UnityTableTool。");
        builder.AppendLine("// Generated by UnityTableTool. Do not edit.");
        foreach (var field in document.Schema.Fields.Where(field => field.Type.IsEnum))
        {
            var enumName = ToEnumName(field);
            builder.AppendLine($"public enum {enumName}");
            builder.AppendLine("{");
            foreach (var value in field.Type.EnumValues ?? [])
            {
                if (!IsIdentifier(value)
                    || IsCSharpKeyword(value))
                    throw new InvalidOperationException($"枚举字段“{field.Name}”的值“{value}”不是合法的 C# 标识符。");
                builder.AppendLine($"    {value},");
            }
            builder.AppendLine("}");
        }
        builder.AppendLine($"public sealed class {document.Schema.Name}Data");
        builder.AppendLine("{");
        foreach (var field in document.Schema.Fields)
            builder.AppendLine($"    public {ToCSharpType(field)} {ToPascal(field.Name)};");
        builder.AppendLine("}");
        return builder.ToString();
    }

    public static bool IsValidEnumMember(string value) =>
        IsIdentifier(value) && !IsCSharpKeyword(value);

    private static string ToCSharpType(FieldSchema field)
    {
        var type = field.Type;
        var result = type.BaseType switch
        {
            "int" => "int",
            "long" => "long",
            "float" => "float",
            "double" => "double",
            "bool" => "bool",
            "string" => "string",
            "enum" => ToEnumName(field),
            _ => type.BaseType
        };
        return result + string.Concat(Enumerable.Repeat("[]", type.Dimensions));
    }

    private static string ToEnumName(FieldSchema field) => $"{ToPascal(field.Name)}Value";

    private static bool IsCSharpKeyword(string value) => value switch
    {
        "class" or "namespace" or "public" or "private" or "protected" or "internal" or "void"
            or "int" or "long" or "float" or "double" or "bool" or "string" or "enum" or "new" => true,
        _ => false
    };

    private static bool IsIdentifier(string value) =>
        !string.IsNullOrWhiteSpace(value)
        && (char.IsLetter(value[0]) || value[0] == '_')
        && value.Skip(1).All(character => char.IsLetterOrDigit(character) || character == '_');

    private static string ToPascal(string name) => string.IsNullOrEmpty(name) ? name : char.ToUpperInvariant(name[0]) + name[1..];
}
