using System.Text;
using TableTool.Core.Models;
using TableTool.Core.Parsing;

namespace TableTool.Serialization;

public static class CSharpExporter
{
    public static string Export(TableDocument document)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// Generated by UnityTableTool. Do not edit.");
        builder.AppendLine($"public sealed class {document.Schema.Name}Data");
        builder.AppendLine("{");
        foreach (var field in document.Schema.Fields)
            builder.AppendLine($"    public {ToCSharpType(field.Type)} {ToPascal(field.Name)};");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string ToCSharpType(TypeDescriptor type)
    {
        var result = type.BaseType switch
        {
            "int" => "int",
            "long" => "long",
            "float" => "float",
            "double" => "double",
            "bool" => "bool",
            "string" => "string",
            _ => type.BaseType
        };
        return result + string.Concat(Enumerable.Repeat("[]", type.Dimensions));
    }

    private static string ToPascal(string name) => string.IsNullOrEmpty(name) ? name : char.ToUpperInvariant(name[0]) + name[1..];
}
